{
    'name': "School Management",
    'summary': "School Management Module with OpenStreetMap Integration",
    'description': """ This School Management Module is useful for Maintained the Student,Classes,School Transport and Hostel and More features of School. Now includes interactive OpenStreetMap integration for bus route visualization.""",
    'author': 'Lumicute',
    'company': 'Lumicute',
    'maintainer': 'Lumicute',
    'website': "https://lumicute.com/",
    "license": "AGPL-3",
    'category': 'Education',
    'version': '18.0.1.0.0',
    'depends': ['base', 'contacts', 'hr', 'web', 'fleet', 'mail', 'website'],
    'data': [
        'security/ir.model.access.csv',
        'views/geocode_wizard_view.xml',
        'data/cron_jobs.xml',
        'data/student_data.xml',
        'data/teacher_data.xml',
        'views/server_actions.xml',
        'views/student.xml',
        'views/parent.xml',
        'views/student_document.xml',
        'views/classes.xml',
        'views/subject.xml',
        'views/teacher.xml',
        'views/exam.xml',
        'views/exam_result.xml',
        'views/transport.xml',
        'views/transport_iot_view.xml',
        'views/map_template.xml',
        'views/fee.xml',
        'views/hostel.xml',
        'views/fee_type.xml',
        'views/library.xml',
        'views/library_issue.xml',
        'views/school_routes_template.xml',
        'data/demo_danang_routes.xml',
    ],
    'demo': [
    ],
    'images': ['static/description/banner.gif'],
    'installable': True,
    'application': True,
    'auto_install': False,
    'external_dependencies': {'python': ['requests']},
}